### ISSUE TITLE
Conflicts with static::framework(); in html/bootstrap.php

### ISSUE THREAD

**Issue by ghost** [mbabker/bs3-demo#2]
https://github.com/joomla/joomla-cms/pull/6858#issuecomment-105082373

More a question...

Hello, thanks for this plugin idea!
I started with 2 friends to set up a plugin that loads BS3 methods/css/less/js, basic "BS2toBS3-translation files" for grid etc. from its own media folder to make it usable for several templates without redundant bootstrap overrides in each template folder (but with possibility to override anything from template folders if wanted).

We also established an override for the bootstrap framework itself

```
if (!JHtml::isRegistered('bootstrap.framework'))
{
 JHtml::register('bootstrap.framework', 'PlgSystemBS3tmpl::framework');
}
```

Some of methods in
/libraries/cms/html/bootstrap.php
work also with BS3. So, no need to override them inside plugin.

But these methods are calling the framework via

```
// Include Bootstrap framework
static::framework();
```

and not via JHtml. Thus BS2-JS is also loaded and kills BS3.
My idea was to replace these lines with (which works fine)

```
JHtml::_('bootstrap.framework');
```

but it's a core file.

Other idea was to make

```
protected static $loaded = array();
```

public (but did not test it, if this makes sense).

Maybe you have an idea and time to answer...

(BTW: this is not a commercial project)

**Comment by mbabker** [comment]
I'd say send a PR to Joomla with the change explaining why.  Definitely should be changed to enable the override system to work.
